// Jenkinsfile

pipeline {
        agent {
            docker {
                image 'maven:3-alpine'
                args '-v /root/.m2:/root/.m2 -v /var/run/docker.sock:/var/run/docker.sock'
            }
        }
        stages {
                stage('Build') {
                    steps {
                        sh 'mvn -B -DskipTests clean package'
                    }
                }
                stage('Deploy') {
                    steps {
                        sh 'set -x'
                        sh 'mvn jar:jar install:install help:evaluate -Dexpression=project.name'
                        sh 'set +x'
                        sh 'set -x'
                        sh 'NAME=`mvn help:evaluate -Dexpression=project.name | grep "^[^\[]"`'
                        sh 'set +x'
                        sh 'set -x'
                        sh 'VERSION=`mvn help:evaluate -Dexpression=project.version | grep "^[^\[]"`'
                        sh 'set +x'
                        sh 'set -x'
                        sh 'java -jar target/${NAME}-${VERSION}.jar'
                    }
                }
            }
}
