// Jenkinsfile

pipeline {
        agent {
            docker {
                image 'maven:3-alpine'
                args '-v /var/run/docker.sock:/var/run/docker.sock'
            }
        }
        stages {
                stage('Build') {
                    steps {
                        sh 'mvn -B -DskipTests clean package'
                    }
                }
                stage('Deploy') {
                    steps {
                        sh './jenkins/scripts/deliver.sh'
                    }
                }
            }
}
